---
- name: Install Java
  hosts: "{{hosts}}"
  become: yes
  roles:
    - role: geerlingguy.java

- name: Set up Spigot server
  hosts: "{{hosts}}"
  become: yes
  tasks:
  - name: Create Spigot directory
    file:
      path: "{{spigot_dir}}"
      state: directory

  - name: Download BuildTools
    get_url:
      url: https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      dest: "{{spigot_dir}}/BuildTools.jar"
