---
- name: Install Java
  hosts: "{{hosts}}"
  become: yes
  roles:
    - role: geerlingguy.java

- name: Set up Paper server
  hosts: "{{hosts}}"
  become: yes
  tasks:
  - name: Create Paper directory
    file:
      path: "{{paper_dir}}"
      state: directory

  - name: Download Paper
    get_url:
      url: https://papermc.io/api/v1/paper/1.15.1/42/download
      dest: "{{paper_dir}}/paper.jar"
      force: no
